import Head from 'next/head';
import Template1 from 'components/resume/Template1';

const data = {
    name: 'Cirhan Yaqoob',
    designation: 'MERN Stack Developer',
    contact: {
        email: 'khancirhan@gmail.com',
        phone: '+91 9797790498',
        address: 'Srinagar, Jammu & Kashmir',
        linkedIn: 'linkedin.com/in/khancirhan/',
    },
    about: `Highly-skilled and motivated senior software engineer with 3 years of experience.`,
    skills: [
        { title: 'Languages', values: ['Javascript', 'Java', 'Python', 'PHP', 'HTML 5', 'CSS 3'] },
        {
            title: 'Frameworks',
            values: [
                'Express.js',
                'React.js',
                'Next.js',
                'Angular',
                'Bootstap',
                'Tailwind CSS',
                'JQuery',
                'Flask',
                'Django',
                'Spring Boot',
            ],
        },
        {
            title: 'Databases',
            values: ['MySQL', 'MongoDB'],
        },
        {
            title: 'Other',
            values: ['REST APIs', 'Microservices', 'Socket.io', 'GraphQL'],
        },
    ],
    experiences: [
        {
            title: 'Senior Product Developer',
            company: 'Codeus IT Solutions Pvt Ltd',
            timeFrame: '11/2020 - Present',
            achievements: ['Rewrote existing software using latest technologies and best practices.'],
        },
        {
            title: 'Full Stack Web Developer',
            company: 'Freelancing',
            timeFrame: '04/2020 - 10/2020',
            achievements: [
                'Developed order-processing module that interfaces with Ebay’s Order and Shipment APIs.',
                'Created product-catalog module for adding and listing all products.',
                'Designed RESTful APIs using spring-boot and built frontend interface using angular.',
            ],
        },
        {
            title: 'Intern',
            company: 'Grey Delta',
            timeFrame: '06/2019 - 12/2019',
            achievements: ['Worked on an inventory management project for a seller'],
        },
    ],
    educations: [
        {
            degree: 'Bachelor of Engineering in Computer Science',
            school: 'University of Kashmir, Hazratbal, Srinagar',
            timeFrame: '2015 - 2019',
            grade: '8.1 GPA',
        },
        {
            degree: 'Higher Secondary from JKBOSE',
            school: 'SP College, Srinagar',
            timeFrame: '2012 - 2014',
            grade: '90.2%',
        },
    ],
    projects: [
        {
            title: 'Livelapse API',
            descriptionList: ['A sophisticated API for image stitching and processing.'],
            link: '',
        },
        {
            title: 'TheQuantum',
            descriptionList: [],
            link: 'https://quantam.io',
        },
        {
            title: 'HarisaByKilo',
            descriptionList: [],
            link: 'https://harisabykilo.com',
        },
    ],
};

const Resume = () => {
    return (
        <>
            <Head>
                <title>Cirhan Yaqoob - Resume</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Template1 data={data} />
        </>
    );
};

export default Resume;
