/* eslint-disable @next/next/no-img-element */
import PortfolioCard from 'components/portfolio/PortfolioCard';
import ServiceCard from 'components/services/ServiceCard';
import Navbar from 'components/shared/Navbar';
import { ArrowLeftIcon, ArrowRightIcon, GithubIcon, LinkedInIcon, MailIcon, PhoneIcon, WhatsappIcon } from 'icons';
import Head from 'next/head';
import { Swiper, SwiperSlide } from 'swiper/react';
import styles from 'styles/Index.module.scss';

const Home = () => {
    const sliderOptions = {
        spaceBetween: 32,
        slidesPerView: 1,
        breakpoints: {
            320: {
                slidesPerView: 1,
            },
            640: {
                slidesPerView: 2,
            },
            1024: {
                slidesPerView: 3,
            },
            1536: {
                slidesPerView: 4,
            },
        },
        navigation: {
            prevEl: '.prev-btn',
            nextEl: '.next-btn',
        },
    };

    return (
        <>
            <Head>
                <title>Cirhan Yaqoob - Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />

            <div className={styles['gradient-left']}></div>

            <div className={styles['gradient-right']}></div>

            <section id="home" className="min-h-screen pt-[68px]">
                <div className="container relative">
                    <div className="pt-[12vh] md:pt-[22vh] text-center">
                        <h1 className="text-white text-center text-5xl md:text-6xl lg:text-7xl font-bold leading-tight md:leading-tight lg:leading-tight">
                            Hey! I’m Cirhan Yaqoob <div className="text-gradient">Full Stack Developer</div>
                        </h1>

                        <p className="mx-auto max-w-3xl text-center mt-6">
                            Product Designer and Digital Creative Director working in design field for 13 years so far,
                            specialized in UI/UX, Branding and digital designs.
                        </p>

                        <button className="btn-lg border border-white/20 text-white mt-16">Say Hello!</button>
                    </div>
                </div>
            </section>

            <section id="about" className="py-16 md:py-40">
                <div className="container">
                    <div className="grid grid-cols-1 gap-24 lg:grid-cols-2">
                        <div className="col-span-1">
                            <div className="relative flex">
                                <img
                                    className="relative top-12 left-0 w-[48%] lg:w-[60%] rounded-lg aspect-[2/3] object-cover"
                                    src="https://images.unsplash.com/photo-1520583457224-aee11bad5112?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=930&q=80"
                                    alt=""
                                />

                                <img
                                    className="absolute -top-12 right-0 w-[48%] lg:w-[60%] rounded-lg aspect-[2/3] object-cover"
                                    src="https://images.unsplash.com/photo-1665686306574-1ace09918530?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80"
                                    alt=""
                                />
                            </div>
                        </div>
                        <div className="col-span-1">
                            <h2 className="text-gradient">About Me</h2>

                            <div className="mt-5">
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Turpis scelerisque purus eu
                                    quis lacus, nibh pharetra.
                                </p>

                                <p className="mt-6">
                                    Interdum vitae fames magna tristique massa. Quis tellus tempor, ut sed cursus. Mi
                                    diam cursus interdum est egestas. In at sit tincidunt sed tort.
                                </p>
                            </div>

                            <div className="mt-12">
                                <h6>You can also find me here:</h6>

                                <div className="flex items-center flex-wrap gap-8 mt-6">
                                    <a
                                        target="_blank"
                                        href="https://api.whatsapp.com/send?phone=9797790498"
                                        rel="noreferrer"
                                        className="flex items-center gap-2 text-[#25d366]"
                                    >
                                        <div>
                                            <WhatsappIcon width="32" />
                                        </div>

                                        <div className="font-semibold text-base lg:text-lg">Whatsapp</div>
                                    </a>

                                    <a
                                        target="_blank"
                                        href="https://www.linkedin.com/in/khancirhan"
                                        rel="noreferrer"
                                        className="flex items-center gap-2 text-[#008AD2]"
                                    >
                                        <div>
                                            <LinkedInIcon width="32" />
                                        </div>
                                        <div className="font-semibold text-base lg:text-lg">LinkedIn</div>
                                    </a>

                                    <a
                                        target="_blank"
                                        href="https://github.com/khancirhan"
                                        rel="noreferrer"
                                        className="flex items-center gap-2 text-gray-200"
                                    >
                                        <div>
                                            <GithubIcon width="32" />
                                        </div>

                                        <div className="font-semibold text-base lg:text-lg">Github</div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section id="expertise" className="py-16 md:py-32 overflow-hidden">
                <div className="container">
                    <div className="relative">
                        <div className="flex items-center justify-between">
                            <div>
                                <h2 className="text-gradient">My Expertise</h2>

                                <p className="max-w-2xl mt-5">
                                    Product Designer and Digital Creative Director working in design field for 13 years
                                    so far, specialized in UI/UX, Branding and digital designs.
                                </p>
                            </div>
                        </div>

                        <div className="mt-10 md:mt-16">
                            <Swiper {...sliderOptions} className="overflow-visible">
                                {[1, 2, 3, 4].map((row, i) => (
                                    <SwiperSlide key={i} className="!h-auto">
                                        <ServiceCard />
                                    </SwiperSlide>
                                ))}
                            </Swiper>
                        </div>

                        <div className="flex items-center justify-center gap-8 mt-8 lg:absolute lg:top-0 lg:right-0 lg:mt-0">
                            <button
                                type="button"
                                className="prev-btn w-20 h-20 rounded-3xl bg-darker border border-white/10 text-white flex justify-center items-center disabled:text-gray-500"
                            >
                                <ArrowLeftIcon />
                            </button>
                            <button
                                type="button"
                                className="next-btn w-20 h-20 rounded-3xl bg-darker border border-white/10 text-white flex justify-center items-center disabled:text-gray-500"
                            >
                                <ArrowRightIcon />
                            </button>
                        </div>
                    </div>
                </div>
            </section>

            <section id="portfolio" className="pt-16 pb-24 md:pt-32 md:pb-32">
                <div className="container">
                    <h2 className="text-gradient text-center">My Portfolio</h2>

                    <p className="max-w-3xl text-center mx-auto mt-5">
                        Product Designer and Digital Creative Director working in design field for 13 years so far,
                        specialized in UI/UX, Branding and digital designs.
                    </p>

                    <div className="grid grid-cols-2 gap-8 mt-10 md:mt-20">
                        <div className="col-span-2 lg:col-span-1">
                            <PortfolioCard />
                        </div>
                        <div className="col-span-2 lg:col-span-1">
                            <PortfolioCard />
                        </div>
                        <div className="col-span-2 lg:col-span-1">
                            <PortfolioCard />
                        </div>
                        <div className="col-span-2 lg:col-span-1">
                            <PortfolioCard />
                        </div>
                    </div>

                    <div className="flex justify-center">
                        <button className="bg-gradient text-black btn-lg mt-20 hover:brightness-110">Browse All</button>
                    </div>
                </div>
            </section>

            <section className="py-6 md:py-12">
                <div className="container">
                    <div
                        className={
                            'flex flex-col items-center text-center bg-darker px-9 py-12 md:px-14 md:py-20 rounded-xl ' +
                            styles['contact-gradient']
                        }
                    >
                        <h2 className="text-white">Let’s skyrocket your next project together</h2>

                        <p className="text-white mt-6">Lorem ipsum dolor sit amet</p>

                        <button className="bg-gradient text-black btn-lg mt-10 hover:brightness-110">Contact Me</button>
                    </div>
                </div>
            </section>

            <footer id="contact" className="pt-12 pb-12 mt-10">
                <div className="container">
                    <h2 className="text-center">Let’s Talk!</h2>

                    <div className="flex flex-col md:flex-row items-center justify-center gap-8 mt-12">
                        <div className="w-[300px]">
                            <a href="tel:+919797790498" className="flex flex-col items-center">
                                <div className="">
                                    <PhoneIcon height={32} />
                                </div>
                                <h6 className="font-semibold mt-4">Call me</h6>
                                <p className="mt-2">+91-9797 790498</p>
                            </a>
                        </div>
                        <div className="w-[300px]">
                            <a
                                target="_blank"
                                href="mailto:khancirhan@gmail.com"
                                rel="noreferrer"
                                className="flex flex-col items-center"
                            >
                                <div>
                                    <MailIcon height={32} />
                                </div>
                                <h6 className="font-semibold mt-4">Mail me</h6>
                                <p className="mt-2">khancirhan@gmail.com</p>
                            </a>
                        </div>
                        <div className="w-[300px]">
                            <a
                                target="_blank"
                                href="https://www.linkedin.com/in/khancirhan"
                                rel="noreferrer"
                                className="flex flex-col items-center"
                            >
                                <div>
                                    <LinkedInIcon height={32} />
                                </div>
                                <h6 className="font-semibold mt-4">Follow me</h6>
                                <p className="mt-2">linkedin.com/in/khancirhan</p>
                            </a>
                        </div>
                    </div>

                    <div className="border-b border-white/10 mt-14"></div>

                    <div className="text-center mt-12">All Rights Reserved Cirhan ©</div>
                </div>
            </footer>
        </>
    );
};

export default Home;
