/* eslint-disable @next/next/no-img-element */
import PortfolioCard from 'components/portfolio/PortfolioCard';
import ServiceCard from 'components/services/ServiceCard';
import Navbar from 'components/shared/Navbar';
import { ArrowLeftIcon, ArrowRightIcon, GithubIcon, LinkedInIcon, MailIcon, PhoneIcon, WhatsappIcon } from 'icons';
import Head from 'next/head';
import { useRef } from 'react';
import styles from 'styles/Index.module.scss';
import { Swiper, SwiperSlide } from 'swiper/react';

const Home = () => {
    const navigationPrevRef = useRef(null);
    const navigationNextRef = useRef(null);

    const sliderOptions = {
        spaceBetween: 32,
        slidesPerView: 1,
        breakpoints: {
            320: {
                slidesPerView: 1,
            },
            640: {
                slidesPerView: 2,
            },
            1024: {
                slidesPerView: 3,
            },
            1536: {
                slidesPerView: 4,
            },
        },
        navigation: {
            prevEl: navigationPrevRef.current,
            nextEl: navigationNextRef.current,
        },
        onBeforeInit: (swiper: any) => {
            swiper.params.navigation.prevEl = navigationPrevRef.current;
            swiper.params.navigation.nextEl = navigationNextRef.current;
        },
    };

    return (
        <>
            <Head>
                <title>Cirhan Yaqoob - Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />

            <section className="min-h-screen pt-[68px]">
                <div className="container">
                    <div className="pt-[16vh] md:pt-[20vh]">
                        <h1>
                            Hey! I’m Cirhan Yaqoob <div className="text-primary">Full Stack Developer</div>
                        </h1>

                        <p className="max-w-xl mt-6">
                            Product Designer and Digital Creative Director working in design field for 13 years so far,
                            specialized in UI/UX, Branding and digital designs.
                        </p>

                        <button className="btn-primary btn-lg mt-12">Say Hello!</button>
                    </div>
                </div>
            </section>

            <section className="py-16 md:py-40">
                <div className="container">
                    <div className="grid grid-cols-1 gap-24 lg:grid-cols-2">
                        <div className="col-span-1">
                            <div className="relative flex">
                                <img
                                    className="relative top-12 left-0 w-[48%] lg:w-[60%] rounded-4xl aspect-[2/3] object-cover"
                                    src="https://images.unsplash.com/photo-1520583457224-aee11bad5112?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=930&q=80"
                                    alt=""
                                />

                                <img
                                    className="absolute -top-12 right-0 w-[48%] lg:w-[60%] rounded-4xl aspect-[2/3] object-cover"
                                    src="https://images.unsplash.com/photo-1665686306574-1ace09918530?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80"
                                    alt=""
                                />
                            </div>
                        </div>
                        <div className="col-span-1">
                            <h2 className="text-primary">About Me</h2>

                            <div className="mt-5">
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Turpis scelerisque purus eu
                                    quis lacus, nibh pharetra.
                                </p>

                                <p className="mt-6">
                                    Interdum vitae fames magna tristique massa. Quis tellus tempor, ut sed cursus. Mi
                                    diam cursus interdum est egestas. In at sit tincidunt sed tort.
                                </p>
                            </div>

                            <div className="mt-12">
                                <h6>You Can Find Me also Here:</h6>

                                <div className="flex items-center flex-wrap gap-8 mt-6">
                                    <a
                                        target="_blank"
                                        href="https://api.whatsapp.com/send?phone=9797790498"
                                        rel="noreferrer"
                                        className="flex items-center gap-2 text-[#25d366]"
                                    >
                                        <div>
                                            <WhatsappIcon width="32" />
                                        </div>

                                        <div className="font-semibold text-base lg:text-lg">Whatsapp</div>
                                    </a>

                                    <a
                                        target="_blank"
                                        href="https://www.linkedin.com/in/khancirhan"
                                        rel="noreferrer"
                                        className="flex items-center gap-2 text-[#008AD2]"
                                    >
                                        <div>
                                            <LinkedInIcon width="32" />
                                        </div>
                                        <div className="font-semibold text-base lg:text-lg">LinkedIn</div>
                                    </a>

                                    <a
                                        target="_blank"
                                        href="https://github.com/khancirhan"
                                        rel="noreferrer"
                                        className="flex items-center gap-2 text-[#211f1f]"
                                    >
                                        <div>
                                            <GithubIcon width="32" />
                                        </div>

                                        <div className="font-semibold text-base lg:text-lg">Github</div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section className="py-16 md:py-32 overflow-hidden">
                <div className="container">
                    <div className="flex items-center justify-between">
                        <div>
                            <h2 className="text-primary">My Expertise</h2>

                            <p className="max-w-3xl mt-5">
                                Product Designer and Digital Creative Director working in design field for 13 years so
                                far, specialized in UI/UX, Branding and digital designs.
                            </p>
                        </div>

                        <div className="hidden lg:flex items-center gap-8">
                            <button
                                type="button"
                                className="w-20 h-20 rounded-3xl card-shadow bg-white text-primary flex justify-center items-center disabled:opacity-60"
                                ref={navigationPrevRef}
                            >
                                <ArrowLeftIcon />
                            </button>
                            <button
                                type="button"
                                className="w-20 h-20 rounded-3xl card-shadow bg-white text-primary flex justify-center items-center disabled:opacity-60"
                                ref={navigationNextRef}
                            >
                                <ArrowRightIcon />
                            </button>
                        </div>
                    </div>

                    <div className="mt-10 md:mt-16">
                        <Swiper {...sliderOptions} className="overflow-visible">
                            {[1, 2, 3, 4].map((row, i) => (
                                <SwiperSlide key={i} className="!h-auto">
                                    <ServiceCard />
                                </SwiperSlide>
                            ))}
                        </Swiper>

                        {/* <div className="flex lg:hidden items-center justify-center gap-8 mt-9">
                            <button
                                type="button"
                                className="w-20 h-20 rounded-3xl card-shadow bg-white text-primary flex justify-center items-center disabled:opacity-60"
                                ref={navigationPrevRef}
                            >
                                <ArrowLeftIcon />
                            </button>
                            <button
                                type="button"
                                className="w-20 h-20 rounded-3xl card-shadow bg-white text-primary flex justify-center items-center disabled:opacity-60"
                                ref={navigationNextRef}
                            >
                                <ArrowRightIcon />
                            </button>
                        </div> */}
                    </div>
                </div>
            </section>

            <section className="py-16 md:py-32">
                <div className="container">
                    <h2 className="text-primary">My Portfolio</h2>

                    <p className="max-w-3xl mt-5">
                        Product Designer and Digital Creative Director working in design field for 13 years so far,
                        specialized in UI/UX, Branding and digital designs.
                    </p>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-10 md:mt-16">
                        <div className="col-span-1">
                            <PortfolioCard />
                        </div>
                        <div className="col-span-1">
                            <PortfolioCard />
                        </div>
                    </div>

                    <div className="flex justify-center">
                        <button className="btn-primary btn-lg mt-20">Browse All</button>
                    </div>
                </div>
            </section>

            <section className="py-32 bg-primary">
                <div className="container">
                    <div className="max-w-xl">
                        <h2 className="text-white">Let’s skyrocket your next project together</h2>

                        <p className="text-white mt-5">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Turpis scelerisque purus eu quis
                            lacus, nibh pharetra.
                        </p>
                    </div>

                    <button className="bg-white text-primary btn-lg mt-12">Contact Me</button>
                </div>
            </section>

            <section className="pt-20 pb-24 overflow-hidden">
                <div className="container">
                    <div className="max-w-xl mx-auto">
                        <h2 className="text-primary text-center">
                            Technologies <br /> I&apos;ve worked with
                        </h2>
                    </div>

                    <div className="mt-16">
                        <Swiper spaceBetween={32} slidesPerView={'auto'} className="overflow-visible">
                            {[1, 2, 3, 4, 5, 6, 7, 8, 9].map((row, i) => (
                                <SwiperSlide key={i} className="!h-auto w-auto">
                                    <div className="card card-shadow rounded-3xl px-8 py-6 flex flex-col md:flex-row items-center gap-5">
                                        <img
                                            className="h-16"
                                            src="https://api2.illuminz.com/uploads/firebase_2122446bec.png"
                                            alt=""
                                        />
                                        <h6>Firebase</h6>
                                    </div>
                                </SwiperSlide>
                            ))}
                        </Swiper>
                    </div>
                </div>
            </section>

            <footer className="pt-12 pb-12 border-t border-gray-100">
                <div className="container">
                    <h2 className="text-center">Let’s Talk!</h2>

                    <div className="flex flex-col md:flex-row items-center justify-center gap-8 mt-12">
                        <div className="w-[300px]">
                            <div className="flex flex-col items-center">
                                <div className="">
                                    <PhoneIcon height={32} />
                                </div>
                                <h6 className="font-semibold mt-4">Call me</h6>
                                <p className="mt-2">
                                    <a href="tel:+919797790498">+91-9797 790498</a>
                                </p>
                            </div>
                        </div>
                        <div className="w-[300px]">
                            <div className="flex flex-col items-center">
                                <div>
                                    <MailIcon height={32} />
                                </div>
                                <h6 className="font-semibold mt-4">Mail me</h6>
                                <p className="mt-2">
                                    <a target="_blank" href="mailto:khancirhan@gmail.com" rel="noreferrer">
                                        khancirhan@gmail.com
                                    </a>
                                </p>
                            </div>
                        </div>
                        <div className="w-[300px]">
                            <div className="flex flex-col items-center">
                                <div>
                                    <LinkedInIcon height={32} />
                                </div>
                                <h6 className="font-semibold mt-4">Follow me</h6>
                                <p className="mt-2">
                                    <a target="_blank" href="https://www.linkedin.com/in/khancirhan" rel="noreferrer">
                                        linkedin.com/in/khancirhan
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>

                    <div className="border-b border-gray-100 mt-14"></div>

                    <div className="text-center mt-12">All Rights Reserved Cirhan ©</div>
                </div>
            </footer>
        </>
    );
};

export default Home;
