import Navbar from 'components/shared/Navbar';
import Head from 'next/head';
import { useEffect, useRef, useState } from 'react';
import styles from 'styles/Index.module.scss';
import { useInView } from 'react-intersection-observer';

export default function Home() {
    const { ref: ref1, inView: inView1 } = useInView({
        threshold: 0.3,
    });
    const { ref: ref2, inView: inView2 } = useInView({
        threshold: 0.3,
    });
    const { ref: ref3, inView: inView3 } = useInView({
        threshold: 0.3,
    });

    return (
        <>
            <Head>
                <title>Cirhan Yaqoob - Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar />

            <div className="relative">
                <section
                    ref={ref1}
                    className={`min-h-screen pt-[68px] ${styles['bluish-gradient']} ${inView1 ? styles['active'] : ''}`}
                >
                    <div className="container">
                        <div className="pt-[20vh]">
                            <h1 className="">
                                Hey! I’m Cirhan Yaqoob <div className="text-primary">Full Stack Developer</div>
                            </h1>

                            <p className="max-w-xl mt-8">
                                Product Designer and Digital Creative Director working in design field for 13 years so
                                far, specialized in UI/UX, Branding and digital designs.
                            </p>

                            <button className="bg-primary text-lg rounded-2xl text-white px-10 py-3 font-medium mt-10">
                                Say Hello!
                            </button>
                        </div>
                    </div>
                </section>

                <section
                    ref={ref2}
                    className={`page-section py-24 ${styles['orangish-gradient']} ${inView2 ? styles['active'] : ''}`}
                >
                    <div className="container">
                        <h2>
                            <div className="text-orangish">My Expertise</div>
                        </h2>

                        <p className="max-w-3xl mt-6">
                            Product Designer and Digital Creative Director working in design field for 13 years so far,
                            specialized in UI/UX, Branding and digital designs.
                        </p>

                        <div className="grid grid-cols-3 gap-8 mt-16">
                            <div className="col-span-1">
                                <div className="card px-10 pt-12 pb-16 flex flex-col justify-center items-center text-center">
                                    <div className="w-48 h-48 bg-orangish/10 rounded-4xl flex justify-center items-center"></div>

                                    <h5 className="font-bold mt-10">Web Design</h5>

                                    <p className="mt-5">
                                        We believe direct collaboration with our clients is essential to bringing unique
                                    </p>
                                </div>
                            </div>
                            <div className="col-span-1">
                                <div className="card px-10 pt-12 pb-16 flex flex-col justify-center items-center text-center">
                                    <div className="w-48 h-48 bg-orangish/10 rounded-4xl flex justify-center items-center"></div>

                                    <h5 className="font-bold mt-10">Web Development</h5>

                                    <p className="mt-5">
                                        We believe direct collaboration with our clients is essential to bringing unique
                                    </p>
                                </div>
                            </div>
                            <div className="col-span-1">
                                <div className="card px-10 pt-12 pb-16 flex flex-col justify-center items-center text-center">
                                    <div className="w-48 h-48 bg-orangish/10 rounded-4xl flex justify-center items-center"></div>

                                    <h5 className="font-bold mt-10">System Design</h5>

                                    <p className="mt-5">
                                        We believe direct collaboration with our clients is essential to bringing unique
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

                <section
                    ref={ref3}
                    className={`page-section py-24 ${styles['greenish-gradient']} ${inView3 ? styles['active'] : ''}`}
                >
                    <div className="container">
                        <h2>
                            <div className="text-greenish">My Portfolio</div>
                        </h2>

                        <p className="max-w-3xl mt-6">
                            Product Designer and Digital Creative Director working in design field for 13 years so far,
                            specialized in UI/UX, Branding and digital designs.
                        </p>

                        <div className="grid grid-cols-2 gap-8 mt-28">
                            <div className="col-span-1">
                                <div className="card">
                                    <div className="relative">
                                        <img
                                            className="rounded-t-4xl"
                                            src="https://assets.website-files.com/5f68b761049650bd498e2649/5f692087ca2bad9dfe44ad22_image-portfolio-03-designer-template-p-1080.png"
                                            alt=""
                                        />

                                        <div className="absolute bottom-[-1rem] left-10 bg-white rounded-2xl overflow-hidden">
                                            <div className="h-full w-full bg-greenish/10 px-6 py-2 text-greenish  font-semibold">
                                                Web App
                                            </div>
                                        </div>
                                    </div>

                                    <div className="px-10 pt-9 pb-12">
                                        <h5 className="font-bold ">Web Design</h5>

                                        <p className="mt-5">
                                            We believe direct collaboration with our clients is essential to bringing
                                            unique
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div className="col-span-1">
                                <div className="card">
                                    <div className="relative">
                                        <img
                                            className="rounded-t-4xl"
                                            src="https://assets.website-files.com/5f68b761049650bd498e2649/5f692087ca2bad9dfe44ad22_image-portfolio-03-designer-template-p-1080.png"
                                            alt=""
                                        />

                                        <div className="absolute bottom-[-1rem] left-10 bg-white rounded-2xl overflow-hidden">
                                            <div className="h-full w-full bg-greenish/10 px-6 py-2 text-greenish  font-semibold">
                                                Web App
                                            </div>
                                        </div>
                                    </div>

                                    <div className="px-10 pt-9 pb-12">
                                        <h5 className="font-bold ">Web Design</h5>

                                        <p className="mt-5">
                                            We believe direct collaboration with our clients is essential to bringing
                                            unique
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </>
    );
}
