import Head from 'next/head';
import styles from 'styles/Index.module.scss';

export default function Home() {
    return (
        <>
            <Head>
                <title>Cirhan Yaqoob - Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header
                className={styles['navbar'] + ' fixed top-0 left-0 right-0 flex items-center bg-white h-[80px] z-10'}
            >
                <div className="container">
                    <div className="flex items-center">
                        <div className="flex items-center gap-2">
                            <div className="h-8 w-8 text-white rounded-full bg-primary flex justify-center items-center font-bold text-lg">
                                C
                            </div>
                            <div className="text-xl font-bold tracking-wide">Cirhan</div>
                        </div>
                        <div className="ml-auto flex items-center gap-10">
                            <a className="" href="">
                                Home
                            </a>
                            <a className="" href="">
                                About
                            </a>
                            <a className="" href="">
                                Process
                            </a>
                            <a className="" href="">
                                Blog
                            </a>
                            <a className="" href="">
                                Services
                            </a>
                            <a className="btn-primary px-6 py-2" href="">
                                Contact
                            </a>
                        </div>
                    </div>
                </div>
            </header>

            <main className="min-h-screen pt-[68px]">
                <div className="container">
                    <div className="pt-[20vh]">
                        <h1 className="">
                            Hey! I’m Cirhan Yaqoob <div className="text-primary">Full Stack Developer</div>
                        </h1>

                        <p className="max-w-xl mt-8">
                            Product Designer and Digital Creative Director working in design field for 13 years so far,
                            specialized in UI/UX, Branding and digital designs.
                        </p>

                        <button className="bg-primary text-lg rounded-lg text-white px-10 py-3 font-medium mt-10">
                            Say Hello!
                        </button>
                    </div>
                </div>
            </main>

            <section className="py-24">
                <div className="container">
                    {/* <div className="grid grid-cols-3 gap-8">
                        <div className="col-span-1">
                            <div className="card card-shadow px-10 py-8 flex gap-8">
                                <div className="h-10 w-10 rounded-full bg-primary/20 mt-2" />

                                <div>
                                    <h5>Frontend Developer</h5>
                                    <p className="mt-1">Creates websites</p>
                                </div>
                            </div>
                        </div>
                        <div className="col-span-1">
                            <div className="card card-shadow px-10 py-8 flex gap-8">
                                <div className="h-10 w-10 rounded-full bg-primary/20 mt-2" />

                                <div>
                                    <h5>Frontend Developer</h5>
                                    <p className="mt-1">Creates websites</p>
                                </div>
                            </div>
                        </div>
                        <div className="col-span-1">
                            <div className="card card-shadow px-10 py-8 flex gap-8">
                                <div className="h-10 w-10 rounded-full bg-primary/20 mt-2" />

                                <div>
                                    <h5>Frontend Developer</h5>
                                    <p className="mt-1">Creates websites</p>
                                </div>
                            </div>
                        </div>
                    </div> */}

                    <div className="grid grid-cols-2 gap-8">
                        <div className="col-span-1">{/* <h2>Hi There</h2> */}</div>
                        <div className="col-span-1">
                            <div className="flex gap-6">
                                <div>
                                    <div className="vertical-orientation mt-4">
                                        <div className="mr-[4px] w-[1px] h-16 bg-gray-300"></div>
                                        <span className="text-lg text-gray-400">about me</span>
                                    </div>
                                </div>
                                <div>
                                    <h2>
                                        Need Creative Design? <div className="text-primary"> I can Help You!</div>
                                    </h2>

                                    <p className="mt-6">
                                        Product Designer and Digital Creative Director working in design field for 13
                                        years so far, specialized in UI/UX, Branding and digital designs. These are the
                                        words we live by in everything we do. Every story we tell, every brand we build,
                                        and every interaction we create must not only look beautiful. beautifully, too.
                                    </p>

                                    <h6 className="mt-8">You Can Find Me also Here:</h6>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section className="py-24">
                <div className="container">
                    <div className="text-center">
                        <h2>
                            Services What
                            <div className="text-primary">I Can Offer for You</div>
                        </h2>

                        <p className="max-w-4xl mx-auto mt-6">
                            These are the words we live by in everything we do. Every story we tell, every brand we
                            build, and every interaction we create must not only look beautiful.
                        </p>
                    </div>

                    <div className="grid grid-cols-3 gap-8 mt-14">
                        <div className="col-span-1">
                            <div className="card card-shadow p-8 flex flex-col justify-center items-center text-center">
                                <div className="w-14 h-14 rounded-full bg-gray-200"></div>

                                <h5 className="mt-8">UI/UX Design</h5>

                                <p className="mt-3">
                                    We believe direct collaboration with our clients is essential to bringing unique
                                </p>
                            </div>
                        </div>
                        <div className="col-span-1">
                            <div className="card card-shadow p-8 flex flex-col justify-center items-center text-center">
                                <div className="w-14 h-14 rounded-full bg-gray-200"></div>

                                <h5 className="mt-8">UI/UX Design</h5>

                                <p className="mt-3">
                                    We believe direct collaboration with our clients is essential to bringing unique
                                </p>
                            </div>
                        </div>
                        <div className="col-span-1">
                            <div className="card card-shadow p-8 flex flex-col justify-center items-center text-center">
                                <div className="w-14 h-14 rounded-full bg-gray-200"></div>

                                <h5 className="mt-8">UI/UX Design</h5>

                                <p className="mt-3">
                                    We believe direct collaboration with our clients is essential to bringing unique
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </>
    );
}
